[package]
name = "inspiration"
version = "0.1.0"
authors = ["Danny Clarke <danny.clarke@gimbal.com>"]

[dependencies]
hyper = "0.11.0"
futures = "0.1"
tokio-core = "0.1"
regex = "0.2"

[target.heroku]
version = "1.21.0"